version: '3.8'

services:
  niro-portfolio:
    image: ghcr.io/niro58/niro-portfolio:prod
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.niro-portfolio.rule=Host(`nichita-r.com`) || Host(`www.nichita-r.com`)'
      - 'traefik.http.routers.niro-portfolio.entrypoints=websecure'
      - 'traefik.http.routers.niro-portfolio.tls.certresolver=myresolver'
      - 'traefik.http.services.niro-portfolio.loadbalancer.server.port=3106'
      - 'traefik.http.services.niro-portfolio.loadbalancer.sticky=true'
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'service=niro-portfolio-web'
    env_file:
      - env
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
      placement: {}
    networks:
      - web

networks:
  web:
    external: true
