import Navbar from "@/components/nav/nav";
import ScrollObserver from "@/lib/scroll-observer";
import "@/styles/globals.css";
import "@/styles/prism-coldark-dark.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { StrictMode } from "react";
import { Toaster } from "sonner";

const inter = Montserrat({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ScrollObserver>
        <StrictMode>
          <body className={`scroll-smooth bg-background ${inter.className}`}>
            <Navbar />
            {children}
            <Toaster />
          </body>
        </StrictMode>
      </ScrollObserver>
    </html>
  );
}
